#!/bin/sh
# Provisions bucket-scoped READ-ONLY InfluxDB tokens for the things that
# query history: nginx (injects one into the dashboard's proxied queries)
# and Grafana (its own datasource). Each gets its own token, minted and
# written independently and idempotently -- one already existing does not
# skip the other.
#
# Tokens have to be created here rather than just being another value in
# .env: InfluxDB generates a token's string itself when an authorization is
# created (auth create), there is no way to hand it one, so the value can
# only be known after this runs. nginx and grafana each wait on their own
# file existing (see docker-compose.yml's depends_on) rather than starting
# without one -- silently unable to query history is worse than refusing
# to start.
#
# org/bucket are fixed constants (see influx/entrypoint.sh) -- not user
# input, so nothing to read from .env for them. The admin token used to
# authenticate here is the one influx/entrypoint.sh generated and wrote to
# the same shared volume this container also mounts.
set -eu

ADMIN_TOKEN_FILE=/shared/influx-admin-token
NGINX_OUT=/shared/influx-auth.conf
GRAFANA_OUT=/shared/grafana-token
# uid 472 is grafana/grafana-oss's own non-root user (see grafana/Dockerfile
# -- USER grafana). Written here as root, read there as uid 472, so it has
# to be handed to that uid explicitly, same reasoning as mosquitto's poller
# password and the admin token itself (see mosquitto/init-passwd.sh,
# influx/entrypoint.sh) -- a plain chmod 600 alone would leave it
# root-only-readable and Grafana's entrypoint would just hang on its own
# wait loop.
GRAFANA_UID=472
ORG=eg4poll
BUCKET=energy

if [ -f "$NGINX_OUT" ] && [ -f "$GRAFANA_OUT" ]; then
    echo "read-only tokens already provisioned -- leaving them alone"
    exit 0
fi

: "${INFLUX_URL:?set INFLUX_URL}"

# influxdb's own entrypoint writes the admin token file BEFORE influxd
# starts listening, so by the time `influx ping` succeeds below the file is
# already there -- this wait is just for clarity/a clean error, not
# expected to actually loop in practice.
i=0
until [ -f "$ADMIN_TOKEN_FILE" ]; do
    i=$((i + 1))
    [ "$i" -ge 30 ] && { echo "$ADMIN_TOKEN_FILE never appeared -- did influxdb's own setup fail?" >&2; exit 1; }
    sleep 2
done
ADMIN_TOKEN="$(cat "$ADMIN_TOKEN_FILE")"

# The influxdb container's own setup (DOCKER_INFLUXDB_INIT_MODE=setup) is
# still finishing when this container starts -- wait for it to actually
# answer rather than for the container to merely be running.
i=0
until influx ping --host "$INFLUX_URL" >/dev/null 2>&1; do
    i=$((i + 1))
    [ "$i" -ge 30 ] && { echo "influxdb never became ready" >&2; exit 1; }
    sleep 2
done

BUCKET_ID="$(influx bucket list --host "$INFLUX_URL" --token "$ADMIN_TOKEN" \
    --org "$ORG" --name "$BUCKET" --hide-headers | awk -F'\t' '{print $1}')"
[ -n "$BUCKET_ID" ] || { echo "bucket $BUCKET not found in org $ORG" >&2; exit 1; }

if [ ! -f "$NGINX_OUT" ]; then
    TOKEN="$(influx auth create --host "$INFLUX_URL" --token "$ADMIN_TOKEN" \
        --org "$ORG" --read-bucket "$BUCKET_ID" \
        --description "dashboard read-only (auto-provisioned)" \
        --hide-headers | awk -F'\t' '{print $3}')"
    [ -n "$TOKEN" ] || { echo "token creation returned no token" >&2; exit 1; }

    mkdir -p "$(dirname "$NGINX_OUT")"
    cat > "$NGINX_OUT" <<CONF
# Auto-generated by influx/init-read-token.sh -- do not edit by hand.
# Delete this file and restart the influx-init service to reprovision.
proxy_set_header Authorization "Token $TOKEN";
CONF
    echo "nginx read-only token provisioned, scoped to bucket $BUCKET only"
fi

if [ ! -f "$GRAFANA_OUT" ]; then
    GTOKEN="$(influx auth create --host "$INFLUX_URL" --token "$ADMIN_TOKEN" \
        --org "$ORG" --read-bucket "$BUCKET_ID" \
        --description "grafana read-only (auto-provisioned)" \
        --hide-headers | awk -F'\t' '{print $3}')"
    [ -n "$GTOKEN" ] || { echo "token creation returned no token" >&2; exit 1; }

    mkdir -p "$(dirname "$GRAFANA_OUT")"
    printf '%s' "$GTOKEN" > "$GRAFANA_OUT"
    chown "$GRAFANA_UID" "$GRAFANA_OUT"
    chmod 600 "$GRAFANA_OUT"
    echo "grafana read-only token provisioned, scoped to bucket $BUCKET only"
fi
