#!/bin/sh
# Provisions a bucket-scoped READ-ONLY InfluxDB token for the dashboard's
# nginx proxy, and writes it into an nginx include file. Idempotent: does
# nothing if that file already exists.
#
# The token has to be created here rather than just being another value in
# .env: InfluxDB generates a token's string itself when an authorization is
# created (auth create), there is no way to hand it one, so the value can
# only be known after this runs. nginx waits on this file existing (see
# docker-compose.yml: nginx depends_on influx-init) rather than starting
# without it -- a dashboard silently unable to query history is worse than
# nginx refusing to start.
#
# org/bucket are fixed constants (see influx/entrypoint.sh) -- not user
# input, so nothing to read from .env for them. The admin token used to
# authenticate here is the one influx/entrypoint.sh generated and wrote to
# the same shared volume this container also mounts.
set -eu

ADMIN_TOKEN_FILE=/shared/influx-admin-token
OUT=/shared/influx-auth.conf
ORG=eg4poll
BUCKET=energy

if [ -f "$OUT" ]; then
    echo "read-only token already provisioned -- leaving it alone"
    exit 0
fi

: "${INFLUX_URL:?set INFLUX_URL}"

# influxdb's own entrypoint writes the admin token file BEFORE influxd
# starts listening, so by the time `influx ping` succeeds below the file is
# already there -- this wait is just for clarity/a clean error, not
# expected to actually loop in practice.
i=0
until [ -f "$ADMIN_TOKEN_FILE" ]; do
    i=$((i + 1))
    [ "$i" -ge 30 ] && { echo "$ADMIN_TOKEN_FILE never appeared -- did influxdb's own setup fail?" >&2; exit 1; }
    sleep 2
done
ADMIN_TOKEN="$(cat "$ADMIN_TOKEN_FILE")"

# The influxdb container's own setup (DOCKER_INFLUXDB_INIT_MODE=setup) is
# still finishing when this container starts -- wait for it to actually
# answer rather than for the container to merely be running.
i=0
until influx ping --host "$INFLUX_URL" >/dev/null 2>&1; do
    i=$((i + 1))
    [ "$i" -ge 30 ] && { echo "influxdb never became ready" >&2; exit 1; }
    sleep 2
done

BUCKET_ID="$(influx bucket list --host "$INFLUX_URL" --token "$ADMIN_TOKEN" \
    --org "$ORG" --name "$BUCKET" --hide-headers | awk -F'\t' '{print $1}')"
[ -n "$BUCKET_ID" ] || { echo "bucket $BUCKET not found in org $ORG" >&2; exit 1; }

TOKEN="$(influx auth create --host "$INFLUX_URL" --token "$ADMIN_TOKEN" \
    --org "$ORG" --read-bucket "$BUCKET_ID" \
    --description "dashboard read-only (auto-provisioned)" \
    --hide-headers | awk -F'\t' '{print $3}')"
[ -n "$TOKEN" ] || { echo "token creation returned no token" >&2; exit 1; }

mkdir -p "$(dirname "$OUT")"
cat > "$OUT" <<CONF
# Auto-generated by influx/init-read-token.sh -- do not edit by hand.
# Delete this file and restart the influx-init service to reprovision.
proxy_set_header Authorization "Token $TOKEN";
CONF

echo "read-only token provisioned, scoped to bucket $BUCKET only"
